### ISSUE TITLE
rintrojs tour assumes presence of "Transmit brush" box

### ISSUE THREAD

**Issue by csoneson** [csoneson/iSEE#103]
Just as a reminder, although this could probably be left until the interface is fully fixed.

**Comment by federicomarini** [comment]
I've got that in mind, along with other elements that now are either collpased together, or just slightly reordered.
As you said, waiting for the not-to-be-changed-anymore version of the UI to finalize it.

**Comment by federicomarini** [comment]
Now addressed by b39a5da3160f5eb66d6b74a33637986490d3bb5a.
Waiting for CI to pass, then closing here
