### ISSUE TITLE
Additional documentation notes to fix

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#143]
- [x] Rename all variable references to the `PanelOpen` as `BoxOpen`, to distinguish between the collapsible boxes and the plotting panels.
- [x] Rename general brushing to "point selection" or something appropriate, to better distinguish it from Shiny brushing.
- [x] Consistently use `id` and `id0` instead of `i` and `i0`, respectively, throughout `iSEE.R`, to avoid confusion between the panel ID and more general indexing.
- [x] `\code{\linkS4class{}}` seems a bit overboard? I would be inclined to drop the `\code` for references to the class name itself, to distinguish it from the constructor (as the class name is not actually code). Whatever you choose, use the same thing for all S4 classes.

**Comment by LTLA** [comment]
Some comments about the purpose of `scale_size_area` in the (renamed) `.square_plot` would also be nice, as well as the purpose of `guides(size='none')`.

**Comment by kevinrue** [comment]
In the last couple of commits ( 999aa0a , 3530fde62788e872bbcf57360486fb2a3c2f95fc ):

* I've updated documentation from "brushing" to "point selection" throughout `plotting.R`. I'd rather leave the other R files to the respective code creators/maintainers. Let me know if I've got a piece of code in one of those files, that I forgot about.

* I've added a comment about `guides(size='none')`. However, I'm less familiar with our use of `scale_size_area` in this particular case (parameters `limits = c(0, 1)` and `max_size = 30`).

**Comment by LTLA** [comment]
I'm not sure why the last point is checked off here, a `grep` for "SingleCellExperiment" in the `INTERNAL_*.Rd` files indicates that there is still some inconsistencies.

**Comment by csoneson** [comment]
I don't know if any of `guides(size='none')` and `scale_size_area()` is actually doing anything anymore, since there is no `size` in any `aes()`. When it was introduced (I think in 3242d2efd05f2d888e7fdb2ef292456629f1b0e4), we had `aes(size=Proportion)`.

**Comment by LTLA** [comment]
@csoneson can you double-check whether those commands are functional, and remove them if they're not?

**Comment by LTLA** [comment]
@kevinrue After some thought, `DataFrame`s should probably have `\linkS4class`, see the updated wiki. This needs to be changed throughout the docs; I've already dealt with SCE and ECM.

**Comment by csoneson** [comment]
@LTLA I couldn't see that these commands were doing anything, so they are removed in c4c120a5bef12ca97e07ea92e7da843f6705db9f
