### ISSUE TITLE
Further aesthetic parameters

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#146]
We probably need an additional collapsible box containing the following parameters:

- Point size
- Font size
- Legend placement (right or bottom)

We need the ability to choose the default colour when colouring by nothing (as brushing red on black is sometimes not great) as well as a transparency selector (for very dense plots).

**Comment by LTLA** [comment]
UI elements have been added to the latest `heat`, but need integration with the plotting functions.

**Comment by csoneson** [comment]
Integrated in 9e3b0a317cc5f41cec2974c4e009a1aa216c1100
