### ISSUE TITLE
Zooming for discrete variables

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#171]
I realized that our zooming philosophy contradicts our point selection philosophy for categorical variables.

With the latter, we don't care about the x-jitter (for violin plots) or the x/y-jitter (for square plots), as these don't matter with respect to the actual nature of the data. We only care about the true location of the points during selection, which means that you only need to brush the center without further fiddling.

With the former, any zoom will faithfully represent the selected window. This is probably what I asked for but it contradicts our position above, as we are now respecting the (meaningless) jitter of the points.

I think we should change it so that we show all points with **true positions** in the selected window, even if we have to expand the plot boundaries. This would make zooming consistent with the selection.

**Comment by kevinrue** [comment]
fixed in 34e93799

**Comment by kevinrue** [comment]
fixed by #175
