### ISSUE TITLE
Unit tests for memory reporter

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#172]
Can you do me a favour and add unit tests for `.report_memory()` and `.deparse_for_viewing()`? The former needs special testing for list column fields (e.g., to make sure you get sensible stuff with brushes). The latter also needs testing to ensure that nothing funny happens when `deparse()` is called inside a function - it should be okay, but a few rigorous runs shouldn't hurt. Something as simple as creating an object, deparsing it, and evaluating the commands to ensure you get the same object.

**Comment by csoneson** [comment]
Added in c3a7f490a81c2bf2d71da83c6e26202ad7be429e

**Comment by LTLA** [comment]
Still need some tests for `.deparse_for_viewing()`, unless I'm missing something?

**Comment by csoneson** [comment]
The code generated by `.deparse_for_viewing()` is tested by the `.report_memory()` tests.
