### ISSUE TITLE
Some thoughts on consistency

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#178]
We should probably rename Feature expression plots to Feature assay plots, as it seems as if we are "locking in" to expression data.

We should also refer to categorical variables as "categorical" rather than "discrete". Integers are discrete but are not categorical, for example.

**Comment by LTLA** [comment]
`featAss` is probably too lewd, so will go with `featAssay` instead.

**Comment by federicomarini** [comment]
Guess we can close this?
