### ISSUE TITLE
Faceting options for dot plots

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#181]
Pretty self-explanatory, and it should be easy enough - just add a facet option to the visual parameters, along with the x- and y-axis variables to facet _by_ (these need to be categorical, presumably). 

However, we need to check that this works properly with point selection, and that _ggplot2_ doesn't do some stupid shit when certain levels are not present in particular facet combinations.

**Comment by kevinrue** [comment]
Reminder to self: rename `facetByRowColData` to `facetRowsByColData` , etc.

**Comment by kevinrue** [comment]
Investigation required: Axis ticks (X and Y) are messed up when zooming into a facet square plot

**Comment by kevinrue** [comment]
Axis ticks issue fixed by e90afaeb25bde05de44b5539d2415c18e8985672
I'll mark this issue as closed: it will be available in the next release of the package
