### ISSUE TITLE
Heatmap is not happy when all expression values are the same

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#192]
Try running:

```r
iSEE(sce, heatMapArgs=DataFrame(FeatName=I(list("0610010K14Rik"))))
```

... on the `allen`-derived `sce`. This results in an interpolation failure as the expression of this particular feature is zero across all cells. Silly this may be, but the heatmap should protect against this.

**Comment by csoneson** [comment]
Fixed in 82f95dbe9b886ebc4555d5178a257ccd185fc1e0
