### ISSUE TITLE
Centering, scaling and clustering should be done on the subsetted matrix

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#201]
@csoneson 
Currently this is all done on the full matrix, which does not produce the expected results upon subsetting.

https://github.com/csoneson/iSEE/blob/18a3214d1f17c4e042c10f9a0315aa80e47c7711/R/heatmap.R#L54

**Comment by LTLA** [comment]
See #202. Used a rather clunky method of centering and scaling; see if you can do any better. 

Also note that the code tracker for the heatmap needs updating for the new set of commands, as the select commands are now between the initial data set-up and the centering/scaling.

**Comment by csoneson** [comment]
I don't immediately see a less "clunky" way (the `dplyr` approach would do pretty much the same). I tried it out, can't seem to break it. I also updated the code tracker for the heatmaps.

**Comment by csoneson** [comment]
Fixed in 38296ddce4cfcff4f09d508b421c3a4874bce156, 1b0b2bfe9c4cb94f16420759ff4c45082b5f47e7 and merged
