### ISSUE TITLE
Reduced Dimension Plot

### ISSUE THREAD

**Issue by rh680** [csoneson/iSEE#205]
It would be great to be able to label tSNE/PCA plots with two parameters at once. For example, the condition could be represented by the shape or size of the point while the gene expression is depicted through the colour.

**Comment by kevinrue** [comment]
Hi @rh680 ,

Thank you for your feedback. We haven't forgotten about this issue.
Can you please rename the issue to "Point shaping options for dot plots"?
I think this states more specifically the feature you're requesting.

While offering a dropdown to select a variable for the `shape` aesthetic is straightforward, note that this feature requires the slightly less trivial task of identifying and restricting choices to 'discrete' (i.e., categorical) variables (point shape does not make sense for continuous variables). In other words, if we don't restrict choices to only 'groupable' variables, there is a risk of the app freezing if the default (i.e. first) variable in the dropdown is continuous.
This issue being also relevant for #181 which is ongoing, we'll probably fix both simultaneously, and make it available in the next release.

Best wishes

**Comment by kevinrue** [comment]
Progress report: shape control is implemented in b458acc2194e788b42ee40ebbbbccd6d42e271f5 , although the faceting feature is currently unstable here due to ongoing work

**Comment by kevinrue** [comment]
I'll mark this issue closed by a9b3fb328f43d94527b3a938322e3f9d98977a3c
It will be made available in the next version of the package.
