### ISSUE TITLE
 Load a RDA/RDS file containing the SE object instead of creating an app only for that data?

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#213]
Issue to keep track of a reviewer's comment.
> I don't know if this is possible as it is right now, but it could be an option to load a RDA/RDS file containing the SE object instead of creating an app only for that data? That would open the door to deploy the tool independent of the data. For instance, I can see a scenario where iSEE is installed in a docker container, where the user just starts the image and when opening the browser at localhost:8787, there is an option to load a file with the object.

As it happens, this is one of the many ideas that we had already discussed that in the past, and agreed that it was not ideal for several reasons. A few thoughts, in no particular order of importance:
- 'tours' should _not_ include this feature, if only to prevent users from loading any other data set than the one designed for the tour. As a result, this would require to maintain two version (branches or repositories).
- from a perspective of efficiency, increasingly large data sets can be arbitrarily large (in particular with recent droplet-based scRNA-seq), leading to RDS/RData files (1.1 GB for the TCGA tour) that would take a much longer time to upload, than the effort to deploy a dedicated app instance. 
- from an implementation perspective, this is incompatible with the current implementation of `iSEE`. An instance of the app is configured during the call to `iSEE(se=...)` (before the app is even launched), which -among other things- sets the maximal number of panels of each type based on the assays and metadata (i.e., `memory`). Without going into details, those values would not be recomputed upon loading a new object, which would prevent users from creating panels possible for the new object that weren't for the first object.
- RDA objects are by nature the least ideal file type for this purpose, as they may contain any number of objects with any names, that may mask existing objects in the workspace when loaded (and possibly crash the app altogether). On the other hand, RDS file may contain a single object (in this case a `SummarizedExperiment`). Without going back into the detail of preprocessing that `iSEE(se=...)` applies to the `se` object, the app also offers the possibility of an `ExperimentColorMap` which may not be compatible with the new `SummarizedExperiment` and then require its own button.

Feel free to use this issue for discussing and adding more points pro/con the idea.

**Comment by kevinrue** [comment]
Just crossing my mind now:
While a 'persistent' app deployed on a server may benefit of better performances (e.g. more memory), it would also create versioning issues (objects created using more recent/outdated version of packages installed on the Shiny server). 
The most sustainable solution to that remains an app running locally, where the user may control the version of packages used to generate the input object, run the iSEE app (and if required, update their object and/or the packages loaded in the iSEE namespace)

**Comment by LTLA** [comment]
There are definitely major issues related to panel feasibility, observer instantiation and UI regeneration - the app would essentially have to be restarted. Another potential concern is that of security. We have a lot of `eval` calls, and if we're not careful, it would be possible for a malicious user to insert arbitrary R code (e.g., in the column metadata names) that could get executed. For example:

```r
X <- data.frame(A=1:5)
cmd0 <- "X[,'%s']"
cmd <- sprintf(cmd0, "A', Y <- is.null(write.table(X, file='blah.txt')) && 'B'=='B") 
eval(parse(text=cmd))
```

Lo and behold, you get an extra `blah.txt`. In theory, this should be avoidable with `deparse` calls, but it's very easy to forget to add them.

**Comment by LTLA** [comment]
Or even more obviously, people could put all sorts of functions in the `customColFun` argument. Like `unlink("~", recursive=TRUE)`, or other pleasant surprises.

**Comment by federicomarini** [comment]
Pretty much on the same line as Aaron and Kevin.

It was an initial thought on my side as well, but it just makes more sense to have the app tightly tailored on the object it gets as parameter.

Re: your last example, then the app could be called `i(didnot)SEEthatComing` 😄

**Comment by kevinrue** [comment]
I think it's safe to close this issue with no plan to implement it.
