### ISSUE TITLE
Considering support for custom plots and tables

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#225]
We currently support a custom column plot panel type. This panel type accepts a selection from a column-based plot, performs an arbitrary user-supplied operation to generate coordinates, and then plots those coordinates. This was intended to support arbitrary dimensionality reduction on user-selected subsets of samples. However, I find it distasteful for a variety of reasons:

1. This starts getting into interactive analysis, which better done with R itself rather than via _shiny_. I doubt that a single function would suffice for all possible subsets of cells anyway.
2. The panel type currently allows transmission of a selection made on the recomputed coordinates to other panels. This requires storage of intermediate results, which complicates the app and makes it difficult to ensure that it is always in a valid state. For example, it becomes invalid if another panel receives the selection from the custom column plot but the coordinates have not yet been computed.

I propose converting the custom panel types to "end-point" panels, thus avoiding problematic dependencies in **2**. This does limit us to one round of subsetting as users cannot further subselect cells based on an recomputed dimensionality reduction result, but I'd argue that this is a rare use  case anyway.

The solution to **1** is to, as best as we can, facilitate entry _back_ into R for selected subsets. This requires a button to reproduce the "gating" scheme, without the fluff of the plotting code. One can then use _iSEE_ to spawn a series of reduced dimension plots, hand-pick a bunch of clusters, and then copy the gating code back into an R script for further analysis (e.g., DEG detection, subclustering, and so on).

**Comment by kevinrue** [comment]
closed by #227
