### ISSUE TITLE
Logo (and hexSticker) for iSEE

### ISSUE THREAD

**Issue by federicomarini** [csoneson/iSEE#249]
#euroBioc2018 is closing in, if we want to get the hex stickers done by then, we could finalize the logo and its corresponding sticker.

Sparse ideas on the proposal I had in mind:
- stylised goggles, black
- in the lenses, two plots we could do with iSEE, at best representative ones:
    - tSNE for TCGA, coloured by cancer type
    - some violin-ish like plot
- background: white?
- font: we stick to what others are using - which is ...?
- hex border: in honor of #euroBioc2017 where we conceived this, we can pick up that shade of green.

-> I'll try to put up some draft in powerpoint and make a screenshot of it in the next days.
Thoughts?

**Comment by LTLA** [comment]
Gotta gimme some pics, bro.

**Comment by federicomarini** [comment]
In line with the classic pics or didn't happen 😏

**Comment by csoneson** [comment]
For the font (from https://github.com/Bioconductor/BiocStickers): 
`While it is not mandatory, it is suggested to use the Aller font for the text (available in folder fonts/Aller`

**Comment by federicomarini** [comment]
Update on the status:
https://github.com/federicomarini/BiocStickers/blob/master/README.md

and

https://github.com/federicomarini/BiocStickers/blob/master/iSEE/README.md

Once it is fine for all of us, I'd proceed rapidly to Stickermule, so that we have them for EuroBioc2018

**Comment by csoneson** [comment]
This looks good to me :)

**Comment by kevinrue** [comment]
Same here. I like it!
After that, feel free to start adding it to all our GitHub repos, and perhaps the vignettes too :)

**Comment by federicomarini** [comment]
Following a feedback round with Charlotte, I made the hexagon border a little thicker.
This should give us some flexibility in case the cutting operation on the stickermaker-side is not so perfect as we would hope.
Aaron, if you are fine with it as it is, I'd likely proceed with the order.

**Comment by LTLA** [comment]
Can you make the colours darker? It seems pretty faint to me.

**Comment by federicomarini** [comment]
I'll try one round with fully opaque dots, let me set it up

**Comment by federicomarini** [comment]
This one is opaque, with violins colored by group as well. Plus, increased the size of the dots to prevent the faint effect.

**Comment by federicomarini** [comment]
Ref to commit 844392246921a01fdbdbbfb39f604259e535d184

**Comment by LTLA** [comment]
Don't see it on your fork. Did you push?

**Comment by kevinrue** [comment]
I'm good with the latest linked version. To summarize the improvement: larger sticker borders and bigger/more opaque point. Good to go!

**Comment by csoneson** [comment]
Looks good to me too!

**Comment by federicomarini** [comment]
Seems we're all fine on the object.
Re: order, I'd stick to stickermule.
Prices are the following (https://www.stickermule.com/uses/hexagon-stickers):

|quantity |price |
|:--------|:-----|
|50       |€51   |
|100      |€61   |
|200      |€80   |
|300      |€96   |
|500      |€126  |
|1000     |€191  |

I'd say this can be covered by own money (unless end of the year is coming and we - our universities/institutes - have some money we have to spend anyway?). 
A potential sweet spot is the 300 pieces - 75 each, for abt 25€. Fine with this as well?

**Comment by LTLA** [comment]
Fine, as long as it's payment on delivery.

**Comment by federicomarini** [comment]
From the info on the website, as well as from [here](https://github.com/rstudio/hex-stickers/blob/master/stickermule.md), it seems they charge you after you approve their proof doc.

**Comment by LTLA** [comment]
No, I meant "how am I going to pay you?" or whoever stumps up the cash.

**Comment by kevinrue** [comment]
As far as i remember, I also paid mine at the time of order. Nothing to complain though: they arrived within a week when they initially announced two.

**Comment by federicomarini** [comment]
Would a simple bank wire transfer work (via IBAN)? Otherwise I'll wait for the next time we catch up and the first drinks are on you 😅

**Comment by LTLA** [comment]
Yes, drinks and food were what I was thinking.

**Comment by federicomarini** [comment]
Fine for me, I'm happy to sign up the check for the order then ;)
