### ISSUE TITLE
pkgdown-based static documentation

### ISSUE THREAD

**Issue by federicomarini** [csoneson/iSEE#250]
We are getting close to the freeze day for the release cycle, yet something to think of for the devel branch.

On the dedicated branch, `projsite`, there is an instance of the rendered documentation, which is something we get pretty much for free.

We could even meaningfully group the functions "by topic" and have them nicely rendered in the project page.

What's your feedback on this? You should be able to view it by clicking on the `docs/index.html`, everything should be linked to that. Or to get a raw idea, checkout my other package which has it running https://github.com/federicomarini/ideal

**Comment by kevinrue** [comment]
Oh I forgot to follow up on this. Happy to see it deployed like `ideal`!
Curious to see how the grouping by topic would look like.
As far as I'm concerned, you've got carte blanche to customise this aspect of the GitHub repo. It's not like it affects any package functionality, nor does it require any version bump or anything. Just make sure it doesn't clutter the clutter the package source code that we push upstream, as the Bioc build doesn't need to know about those extra files.

Lastly, let's also just make sure that we don't confuse users about where to find information though (e.g. tweets, blogs). I'd recommend: R help pages > Vignettes > pkgdown. Then separately, the various repositories that we have to showcase tours and custom panels.

**Comment by federicomarini** [comment]
> Curious to see how the grouping by topic would look like.
Pretty much as in ideal. A better example is maybe another pkg of mine -> https://federicomarini.github.io/flowcatchR/reference/index.html
There it was meaningful to collect the function by class type - which also reflects the workflow step.
In the case of iSEE, I'd have to check what relevant groupings would be.

> Just make sure it doesn't clutter the clutter the package source code that we push upstream, as the Bioc build doesn't need to know about those extra files.
Should be fine to have it in the `.Rbuildignore` AFAIK?

Re: confusion. Too many location can become overwhelming, I agree. An advantage would be the better rendering of help pages. Plus, people can see the example results as well. And the rendered vignette also links to the rendered help pages. And, it looks good, but it's more than just that IMHO

**Comment by federicomarini** [comment]
Ah, the only relevant change: to get the news auto-rendered, they would have to be moved to the `NEWS.md` in the root folder of the package, instead of the current `inst/NEWS.Rd`. The new format would be officially supported as well.

**Comment by kevinrue** [comment]
> `.Rbuildignore`
If at all possible, I'd rather keep `master` branch as light as possible. It should be possible to use a `gh-pages` branch (https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)

The only overhead would then be to merge `master` into `gh-pages` every now and then. What do you think?

**Comment by federicomarini** [comment]
Not even that. The GitHub page can be rendered by the content in the `docs` folder, from the master branch.
You can see how it looks like in the `projsite` branch.

**Comment by kevinrue** [comment]
Not a big deal to change the NEWS file format (and location). Sounds good to me.

I understand that the `docs` folder in the `master` branch is possible. But my point is exactly that if we can avoid to weight `master` down with stuff that's not necessary for the bioc build, it's probably better.

What I mean is that this rendered documentation is something that's fairly GitHub-specific. Therefore, if we can keep it to a branch that stays on GitHub (but doesn't get pushed to bioc), it sounds cleaner and everything-in-its-place to me.

**Comment by LTLA** [comment]
I concur with Kevin. Nothing related to this - *nothing* - should contaminate the `master` branch.

**Comment by federicomarini** [comment]
Ok, as of now we can keep it on hold (or see if the gh-pages might work).

I agree with the no pollution rule as well. I was "converted" to using pkgdown via `docs` in master after seeing that it is all in one folder, and that can be excluded from the build via `.Rbuildignore`

**Comment by federicomarini** [comment]
Could [this](https://www.datacamp.com/community/tutorials/cd-package-docs-pkgdown-travis) be an acceptable workaround?

**Comment by kevinrue** [comment]
Sounds like it's more than acceptable, from what I read it's bang-on:
> We do not have to specify the GitHub target branch where the docs have to be pushed to, as it defaults to gh-pages.

Plus it only triggers when pushing on the `master` branch (i.e, when we're happy to merge new code ourselves):
> The on field tells Travis to do this deployment step if the change that triggered a build happened on the master branch.

**Comment by federicomarini** [comment]
Uh, this one is probably even better:
https://github.com/r-lib/pkgdown/blob/master/R/deploy-site.R

Combined with...
https://github.com/tidyverse/ggplot2/blob/765f4de737322997c9eb223f4a1656d76f1e0119/.travis.yml#L17-L20

**Comment by kevinrue** [comment]
Closing this issue is overdue. See: https://csoneson.github.io/iSEE/
