### ISSUE TITLE
achieving identical geometries with different legends

### ISSUE THREAD

**Issue by vjcitn** [csoneson/iSEE#252]
![comment](https://user-images.githubusercontent.com/4624066/47542019-72174380-d8a9-11e8-8155-fec8a4531d95.png)

these displays have identical height and width settings but the many legend levels in the 
panel on the right lead to shrinkage of the vertical axis (relative to that on the left).  i wonder if the
plot space could be protected from encroachments by legend.  making the height slider have a smaller
step size might allow better matching.  in this case the jump from 600 to 650 means the two graphs never agree on vertical axis.

**Comment by kevinrue** [comment]
Hm. That's not an easy one for separate panels. In fact, even giving more resolution to the panel height would only lead to more fiddling on the user part, and never lead to the true match that you (or anyone, really) would expect.

Can I ask you to consider [custom panels](https://bioconductor.org/packages/devel/bioc/vignettes/iSEE/inst/doc/custom.html) for this purpose?
Those are currently available only on the development version, but they will be part of the next Bioconductor release on [Wednesday October 31](https://bioconductor.org/developers/release-schedule/).
I just happen to have recently added an example that you might find relevant [here](https://github.com/kevinrue/iSEE_custom/tree/Multireddim/plot_multiRedDim).
If you're familiar with the `cowplot` package, you'll know that one can combine multiple plots in one figure, and align the multiple plot vertically and/or horizontally, the two arguments relevant to the point being demonstrated below
```
cowplot::plot_grid(plotlist=list(your_ggplot_1, your_ggplot_2), align = "h")
```

You'll need to tweak the custom function in the linked example to color the two plots by different covariates, which can be setup as custom arguments, as per documentation linked above. Let me know if you need any help.

**Comment by LTLA** [comment]
As Kevin says, it would be challenging to guarantee a match, for various reasons.

- The height is controlled at the _shiny_ level during rendering of the entire UI. However, the legends are controlled at the _ggplot2_ level, and there's no easy way to make them talk to each other.
- The size of the legend itself depends on what data variables you use for colouring, which is not known at the time of UI rendering. This would require re-rendering of the entire UI when colours are changed.
- Any change to the height bar triggers a UI re-rendering. I should mention that these re-renderings involve regeneration of the plots; so fine-scale fiddling of panel height may become quite expensive.

I don't have any real solution other than to suggest flipping the legend to the left (see "Other" options in the visual box). Then at least the plots will match up vertically; width discrepancies are probably less noticeable when you're comparing plots side by side.

**Comment by kevinrue** [comment]
Note to self: we could also add a checkbox to optionally hide the legend altogether (`+ guides(color="none", shape="none", size="none", alpha="none")`). That would allow the plots to match no matter what, with the caveat that users would need to know their color coding (check out the [ExperimentColorMap](http://bioconductor.org/packages/devel/bioc/vignettes/iSEE/inst/doc/ecm.html) to help with that)

**Comment by kevinrue** [comment]
One more developer note.
I'll also point out that `ggplot2` allows control over the number of rows/columns that legend levels may be split over:
```
guide_legend(nrow = NULL, ncol = NULL)
```
We could potentially add a numeric dropdown (`1:length(nlevels)`). Note that this would need to be reasonably combined with the `theme(legend.position)` setting already proposed by iSEE.

**Comment by LTLA** [comment]
The current `master` has more granular height control, so you can tune it to match up between two plots if you should so wish. Note that the panel organization controls have been moved to the top-left.

**Comment by LTLA** [comment]
I'm going to say that this is probably good enough.
