### ISSUE TITLE
Brushing: the dream

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#26]
We should have brushing enabled on all plots where cells are the dots. The aim is to brush on one plot and see the results on **any** cell-based plot in **any** of the tabs.

This should be very possible, the question is how reactive it should be. Full reactivity would be too slow for large numbers of plots; I am more inclined to have a button on the left with "highlight selected" that a user can press once they've gotten the points they want. Such a button could also be plot-specific, making use of another collapsible box in the plotting parameters for each plot.

**Comment by LTLA** [comment]
Partially addressed in #29, but waiting for custom _ggplot_ calls instead of going via _scater_ to achieve this for all plots.

**Comment by davismcc** [comment]
I find the "brushing" confusing. The term itself is not familiar to me, so I don't immediately intuit what it should do and the help doesn't explain it in enough detail. I suggest we have a help item particularly for brushing that could pop up for people to see/remind what it is without going through the tour again.

**Comment by federicomarini** [comment]
the "brushing" in context of interactive plot is to be intended in the shiny-way, i.e. as in https://shiny.rstudio.com/articles/plot-interaction.html.

Another way to call it would be something related to "linking plots" to something, or also linked plots.

I think the first time I saw the brushing in this context was from an excellent book of Tamara Munzner, but I can think not everyone is familiar with the context.
I'll add one item to the intros tour to tell what the user can do with it.

**Comment by LTLA** [comment]
Done in #65.
