### ISSUE TITLE
iSEE web sockets timing out in Kubernetes

### ISSUE THREAD

**Issue by anton-khodak** [csoneson/iSEE#266]
iSEE apps grey out after 60s of inactivity when deployed on Kubernetes. Javascript console shows "TypeError: this.$socket is null" when trying to click on the greyed out area. 

A few experiments conducted:
* no grey out with a simple Docker deployment (no Kubernetes);
* grey out with an Ingress controller: nginx-ingress, heptio-contour;
* grey out with just a LoadBalancer with no Ingress controller in front;
* grey out with memory requests (guaranteed resources for a container).

So the problem is that Kubernetes internally has some timeout for dropping web sockets connections, but I can't find where when there is no reverse proxy as in the case with just a LoadBalancer. But with JupyterHub, for example, we don't experience problems in a similar setup, so it might also be in the way how iSEE use web sockets.

I understand that it is most likely a problem of the Kubernetes configuration exclusively, but it would be great if someone shared their solution on reliable K8s iSEE deployment.

**Comment by anton-khodak** [comment]
Also, there was a bit of emailing regarding the case containing some important troubleshooting information that should probably be made public as it might be useful to someone in the future. 

Vladimir Kiselev writes:

> We have made the docker images based on your examples. When we run them locally on our laptops, everything works fine. However, when we deploy them on the cloud they start well but then grey out after some time. Apparently, it’s a known issue, but now one provides a good solution:
https://www.google.com/search?ei=yso4XPe8HLSz1fAPn9W8qAw&q=shiny+app+grey+out&oq=shiny+app+grey+out&gs_l=psy-ab.3..0i13j0i13i5i30.5279.9143..9382...0.0..0.100.796.12j1......0....1..gws-wiz.......0i71j35i304i39j35i39j33i10j33i22i29i30j0i13i30.e8tfzNMDGvU
 
> There is a good solution here to customize Shiny server, but in our case,  we do not explicitly use the server, right?
https://stackoverflow.com/questions/44397818/shiny-apps-greyed-out-nginx-proxy-over-ssl

> Have you had this problem with your deployments, by any chance? Any help is appreciated.

> Also, is there a way of running iSEE using a Shiny server (putting something in the shiny server folder)?
 

A response from Kevin Rue-Albrecht:
> When you say “after some time”, I assume you’re not simply hitting the “idleness” timeout? (https://docs.rstudio.com/shiny-server/#session-timeouts)
Could you please describe in more details the circumstances in which the app greys out?
From your description, it sounds like the app initialization runs fine (meaning that panels and data do show up), am I correct?
Then, I don’t understand whether:
You leave the app inactive, and after some time of inactivity it greys out
You can interact with the app for a while, and then either after some specific action or seemingly randomly, the app greys out.
 
> That said, among the “most common reasons” listed in the top comment (1 up-vote) of the first link that you included, I would suspect “Your application requires more memory than the default size accomodates”. Early on, before I knew better, I did have some apps greying out because I wasn’t giving enough memory to the Docker process.
Is there a chance that you’ve configured Docker on your laptop as indicated here (https://docs.docker.com/docker-for-mac/):
Memory: By default, Docker for Mac is set to use 2 GB runtime memory, allocated from the total available memory on your Mac. To increase RAM, set this to a higher number; to decrease it, lower the number.
but that your Cloud solution does not give the image enough memory to run comfortably?
 
> I don’t know how your Cloud is set up, but is it also possible that you deploy multiple images on the same cloud instance and that they compete for memory?
 
> Just to be clear – as I understand it, you’re trying to deploy the demo apps that we’ve made publicly available onhttps://github.com/LTLA/iSEE2018/tree/master/tours/allen, right? Or are you trying to deploy your own apps already? I would make sure that one small app run fine before tackling larger ones. I’ve just tested the following:
https://hub.docker.com/r/kevinrue/isee_tcga and `docker stats` declares a memory usage of 1.017 GB.
https://hub.docker.com/r/kevinrue/isee_allen and `docker stats` declares a memory usage of 1.193 GB.
> Aaron will have more experience to talk about the use of Shiny Server. My institute is still in the process of setting it up; I’ve used Shiny server in the past, but not with iSEE yet.

Aaron Lun adds:
> Using the Shiny server is as easy as throwing all an “app.R” file into a directory, along with the RDS of the SE that you want to look at. It just worked for me.
 
> Admittedly, our IT team may have done some configuring of the server beforehand; I wasn’t privy to the details. But whatever they did, it wasn’t iSEE-specific.

**Comment by kevinrue** [comment]
Thanks for posting the conversation here. Hopefully it will help other users with a similar issue and perhaps bring in more help from other Kubernetes users!

**Comment by LTLA** [comment]
I'm going to assume this was either resolved or not our problem.
