### ISSUE TITLE
The ideal history log

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#27]
We should get something similar to `ideal` in reporting the commands used to generate each plot. This makes it very easy for people to copy-paste the commands to generate the plot after it's been done.

**Comment by federicomarini** [comment]
We can consider this solved after https://github.com/csoneson/iSEE/pull/67

**Comment by LTLA** [comment]
Almost. Can you merge `master` into `brush_integration`? (Not the other way around, at least not yet.) There are probably two elements that need to be added to the top of `codetrack.R`:

- `se <- XXX` where `XXX` is the variable name for the input object; see Slack discussions.
- `all.coordinates <- list()` to enable storage of brushed points.

**Comment by federicomarini** [comment]
I did not catch up with the brushing part, but I'll look into it.
Merged the newest version to track code also here in `brush_integration`

**Comment by kevinrue** [comment]
I can still add `se <- XXX` before merging to `master`. Not sure what you mean about `all.coordinates` though

**Comment by LTLA** [comment]
You'll notice in `iSEE.R` that every transmitting plot (i.e., with `.brushActive` field being `TRUE`) adds a command to store the plot coordinates into `all.coordinates`. This ensures that a separate receiving plot can properly determine the points that were brushed in the transmitting plot. Obviously, this also means that we need to define `all.coordinates` at the start of the code output by `code_track.R`.

**Comment by kevinrue** [comment]
Indeed. Not sure how to best do this, so I'll leave it for tomorrow or one of you.

**Comment by kevinrue** [comment]
Note to self (and users):
I was going to ask whether the tracker could include a button 'copy to clipboard' , out of laziness to drag my mouse over all the script.
However, I just noticed that one can click inside the aceEditor and then hit Cmd-A to select everything.

**Comment by LTLA** [comment]
Fixed with fbff388db2ab31ea7c8b9372a9d17f68d3c01a41, closing.
