### ISSUE TITLE
Fix test_zzz.R

### ISSUE THREAD

**Issue by LTLA** [csoneson/iSEE#284]
This is failing. The new path should really be:

```r
shiny:::.globals$resourcePaths$iSEE$path
```

... though I can't say I'm happy about poking around in _shiny_'s unexported objects.

**Comment by LTLA** [comment]
Changed this in #285 but @kevinrue should really decide if this test is even necessary, given it seems that you commented out the actual `expect_*` line anyway.

**Comment by LTLA** [comment]
And propagate the fix to release, which is broken for the same reason.

**Comment by kevinrue** [comment]
fixed in d077eefa69f3aceee09d60598e8acc114262fdbd
