### ISSUE TITLE
Coloring a point by "sample name" or "feature name" does not work if the point was downsampled

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#295]
- Launch the example `?iSEE` app
- Set the Column data plot axes to "NREADS" AND "NALIGNED"
- Enable downsampling to resolution 200 
- Color by "Sample name"
- Link to "Column statistics table"
- Select the first row: no point is highlighted
- Select the second row: the point is highlighted

**Comment by csoneson** [comment]
Fixed by random downsampling in 8241e84
