### ISSUE TITLE
modeVoid(...)

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#303]
A mode that - no matter the preconfigured panel parameters - launches an app with no panel initially visible.

Basically just a shorthand for:
```
initialPanels <- DataFrame(Name=character(0), Width=integer(0), Height=integer(0))
iSEE(..., initialPanels=initialPanels)
```

I would expect this to become a popular mode to launch "empty" apps rapidly (as there are no plots to render) with users adding necessary panels, in contrast to the current behaviour of `iSEE()` which generates a panel of each type (time consuming) with users removing panels (wasting more time rendering the interface again).

**Note**: Incidentally, if we're thinking of implementing more modes, I also propose to rename modes `mode_<name>` (snake_case), in contrast to the current `mode<Name>` (camelCase). Opinions?

**Comment by federicomarini** [comment]
More than opinions, data survey 😄 
https://github.com/chainsawriot/rstyle/blob/master/user2019_poster.pdf
