### ISSUE TITLE
Support zero-row initialPanels 

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#304]
While implementing #303 I noticed that :
```
initialPanels <- DataFrame(Name=character(0), Width=integer(0))
iSEE(sce, initialPanels=initialPanels)
```
crashed with error
```
 Error in `[[<-`(`*tmp*`, name, value = 500L) : 
  1 elements in value to replace 0 elements 
```
Basically, because our code was trying to initialise missing columns (e.g., `Height`) with a vector of length > 0

**Comment by LTLA** [comment]
shuold be simple, just wrap the height assignment with `rep()`.

**Comment by kevinrue** [comment]
It is. That was just a reminder to myself as I ran out of steam/time yesterday.
