### ISSUE TITLE
Gene statistics table with many columns

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#31]
Gene statistics table with many columns go out of screen. We should probably allow users to select a subset of columns to show, with default settings being e.g. the first 5 or 10 columns.

**Comment by csoneson** [comment]
We can allow horizontal scrolling to potentially avoid this problem.

**Comment by kevinrue** [comment]
That is absolutely true.  I opened this issue because I couldn't naturally scroll to the later columns, and I cannot remember if/how this can be enabled in Shiny apps.

**Comment by federicomarini** [comment]
`options = list(scrollX = TRUE)` in the `DT::datatable` should suffice

**Comment by federicomarini** [comment]
Can we close this one?

**Comment by LTLA** [comment]
If someone had fixed it, then yes.

**Comment by federicomarini** [comment]
Should be fixed now in the branch `fede_edits`, soon to be pushed.

Example to see how this allows the horizontal scrolling:

```
## building up on...
example(iSEE,ask = F)
## and slightly editing that `sce` object

rowData(sce) <- DataFrame(primacolonna = sample(1:20908),
                          secondacolonna = paste0("seconda_",sample(1:20908)),
                          terzacolonna = paste0("testobellolungohehe", sample(1:20908)),
                          quartacolonna = paste0("2otestobellolungohehe", sample(1:20908)),
                          quintacolonna = paste0("3otestobellolungohehe", sample(1:20908)))
iSEE(sce)
```

--> and scrolling on the `datatable` object, which now also respects the column width specification

**Comment by LTLA** [comment]
My computer at home doesn't have enough grunt to run `iSEE` (or anything much, for that matter) so I'll assume that `scrollX=TRUE` does a sensible job. It doesn't scroll if it doesn't need to, right?

**Comment by federicomarini** [comment]
Yep, no scroll if not needed. You can check how this is turned on when you resize the window where `iSEE` runs.
