### ISSUE TITLE
optional column with user-friendly gene_name

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#33]
while unique gene ids (e.g. ensemble_gene_id) are necessary to fetch data from the object, it would be nice to let users select an optional column of the Gene statistics table that contains a user-friendly gene symbol to annotate the plot (e.g. `ggplot(...) + labs(subtitle = ...)`).
The widget to select this would be in an expandable "plotting parameters" panel under the Gene statistics table.

**Comment by LTLA** [comment]
A much simpler solution would be for people to change the row names prior to calling `iSEE`.

**Comment by kevinrue** [comment]
I just want to avoid falling in the Seurat choice of `make.unique` on the gene names.

**Comment by LTLA** [comment]
If it's a big deal, I would use the approach in [section 2.3 here](https://bioconductor.org/help/workflows/simpleSingleCell/part1/#incorporating-gene-based-annotation) (I'll move it to _scater_). The fact remains that somewhere along the line, if the gene names are not unique, there needs to be a way to disambiguate them. Hiding the ambiguities would probably be even worse for data exploration.

Moreover, if people want a nicer plot annotation, they can do that outside the app once they have the code from @federicomarini's log. It shouldn't be a particularly complex change.

**Comment by LTLA** [comment]
Closing this, `scater` now has a `uniquifyFeatureNames` option.
