### ISSUE TITLE
Help and tour needs fleshing out

### ISSUE THREAD

**Issue by davismcc** [csoneson/iSEE#54]
Great start there, but missing details to introduce a new users thoroughly

**Comment by federicomarini** [comment]
The implementation as of now (19.01) was more a proof of principle/working prototype
 to tease the others in adding this feature. Once the UI is stably defined I will finalise the text for each tour item

**Comment by kevinrue** [comment]
Was that fully solved by 6c938c38c6fa81c3bb8e10f94ed91f216839106e or are there any more expected updates (apart from iterative fleshing out upon implementation of future features)?

**Comment by federicomarini** [comment]
If updates are coming, they will be minor, I guess.
So 6c938c38c6fa81c3bb8e10f94ed91f216839106e closes the issue
