### ISSUE TITLE
Access help/docs when app is running

### ISSUE THREAD

**Issue by davismcc** [csoneson/iSEE#55]
Standard R help/docs not available when Shiny app is running, so needs to be completely self-explanatory (have sufficient docs/explanation available from app).

**Comment by kevinrue** [comment]
I assume you mean the _prompt_ is not available: RStudio users can still use the 'Help' panel.
As discussed on Slack, we'll ensure comprehensive documentation is available in vignettes and help pages available outside the app. Users will be available to access those elements of documentation while an app is running without interfering with it.
I'll close the issue, as documentation will be added continuously.
