### ISSUE TITLE
Colormap for continuous variables

### ISSUE THREAD

**Issue by davismcc** [csoneson/iSEE#56]
I don't like the default ggplot2 colormap for continuous variables; not a useful scale and too "vanilla" for my liking

**Comment by kevinrue** [comment]
Aside from the actual choice of colours, I've got an evil masterplan to allow custom colour scales being set for individual `colData` and `assay`.
I'll link the commit here as soon as I can get to it.

**Comment by kevinrue** [comment]
fixed by dae2031d0c28a520ab8c854691fdb8405d41dbb8
more accessors/setters and documentation coming soon
