### ISSUE TITLE
Option to add smoothed fit to 2D scatterplots

### ISSUE THREAD

**Issue by davismcc** [csoneson/iSEE#59]
Thinking for gene expression and colData.

**Comment by LTLA** [comment]
That's uncomfortably close to actual analysis, not just visualization.

**Comment by kevinrue** [comment]
Agreed with Aaron. This feature would open the door to 'which kind of fit and parameters' that would turn into a pretty large panels of options.

**Comment by LTLA** [comment]
We give the code for making all the plots, so I think it's fairly reasonable for people to copy-and-paste it into their session and then play around with their own smoothers, rather than us having to support it manually. So I'm closing this.
