### ISSUE TITLE
"Extract R code" doesn't give code to reproduce plots

### ISSUE THREAD

**Issue by davismcc** [csoneson/iSEE#62]
"Extract the R code" looks like it just has variable definitions, but  does not have function calls or the code that would let me reconstruct the plots outside of the app. That's the aim, right?

**Comment by LTLA** [comment]
Yes, that's the aim of #27. @federicomarini will be bringing this to completion.

**Comment by federicomarini** [comment]
Just for pointing to a ref, solved in https://github.com/csoneson/iSEE/pull/67
