### ISSUE TITLE
broken geneExprsPlot for discrete X axis

### ISSUE THREAD

**Issue by kevinrue** [csoneson/iSEE#68]
`.violin_plot` should be called to handle this scenario (X discrete, Y continuous)
check whether `.scatter_plot` gets called instead (that would call `range()` on a discrete value, which doesn't work)

**Comment by LTLA** [comment]
It will call `.scatter_plot` if there's too many values - but there should be a .`coerce_to_numeric` somewhere to protect the `range()` call.

**Comment by kevinrue** [comment]
fixed by 5fa8a02  
need to find a cleaner way to preserve axis ranges upon brushing in restrict mode, for violins

**Comment by LTLA** [comment]
I'm actually fine with restricting the points only, and leaving the violins computed using the full set of data. This is technically most consistent with what brushing is meant to do in the other plots. Recalculation of the violins is nice but conflates the brushing with the plotting.
