### ISSUE TITLE
Violin brushing and subset

### ISSUE THREAD

**Issue by federicomarini** [csoneson/iSEE#84]
One thing I noticed is that when the brushed points are transmitted to a violin and we choose restrict as an option, the violin gets redrawn, because the points set changed.
This does not occur when we apply the color or transparency effects. 
Is this wanted? Or should we plot also the original violins when subsetting?

**Comment by LTLA** [comment]
Yes, this is wanted, and it took a long time to get this working.

**Comment by LTLA** [comment]
Closing this.
